### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by totor321** [nenes25/prestashop_eicmslinks#1]
Bonjour
Sur la dernière version de PS, 1.6.1.4, j'ai toutes les peines du monde pour installer ce module. Il a air vraiment bien fait sur votre tuto mais la méthode d'install est elle différente d'un module classique ?
D'avance merci
Anne-Laure

**Comment by nenes25** [comment]
Bonjour,

L'installation du module est tout ce qu'il y'a de plus classique.
En revanche en raison de son hébergement sur github, il est nécessaire d'envoyer le module via ftp dans un dossier "eicaptcha". ( L'archive générée par github n'a pas le bon nom )

N'hésitez pas à me signaler si vous rencontrez d'autres erreurs.

Cordialement,
Hervé

**Comment by totor321** [comment]
Bonjour
L'install a pu se faire. Par contre 2 choses :
- Est-ce normal que  dans le menu PS de gauche Préférences/Eicmlinks, j'ai d'abord un avertissement clé de sécurité puis une page vide ?
- Les liens produits ne fonctionnent pas. 

Merci pour votre retour
Anne-Laure

**Comment by nenes25** [comment]
Bonjour,

Désolé j'avais mal lu le module concerné par votre demande, du coup la réponse n'est pas tout à fait exacte.

L'installation de ce module est un peu particulière car prestashop impose la création de ce lien dans l'administration pour que les appels admin du module puissent fonctionner. ( Je n'ai pas la possibilité de ne pas l'afficher )
Cependant cette page n'est effectivement pas utilisée, ne tenez pas compte de ce lien.

Quel est le comportement d'erreur pour les produits ?
Les autres liens sont-t-ils fonctionnels ?

Cordialement,
Hervé
