### ISSUE TITLE
Integration in PhenixSuite

### ISSUE THREAD

**Issue by Eolia** [nenes25/prestashop_eicmslinks#6]
Hi @nenes25 !
I don't know if you know this but I'm working on the Prestashop 1.6 version suite (https://eoliashop.com/prestashop-new).
I was thinking of integrating your code natively if you agree.
PhenixSuite natively integrating the hookActionOutputHTMLBefore() I think integrating it quite simply with this kind of function:
`
    public function hookActionOutputHTMLBefore($params) {
            
        if (isset($params['html']) && $params['html']) {
            $params['html'] = preg_replace_callback('~\[HookEicms]~', array($this, 'replaceShortCode'), $params['html']);
        }
    }
`
Let me know if you agree :)

**Comment by nenes25** [comment]
Hi @Eolia ,
Yes I've already download and tested your project , it's a very nice initiative :+1:
Sure feel free to use this code, I'm glad if it could helps 

Regards,

**Comment by Eolia** [comment]
It's done ;)

[https://www.prestashop.com/forums/topic/1070358-sortie-de-la-version-16128-by-eolia/?do=findComment&comment=3455457](https://www.prestashop.com/forums/topic/1070358-sortie-de-la-version-16128-by-eolia/?do=findComment&comment=3455457)

**Comment by nenes25** [comment]
Nice Job, thanks so i close this issue :smiley:
